### ISSUE TITLE
Problema en Ubuntu Mate 16.04 en Raspberry Pi 3

### ISSUE THREAD

**Issue by lcg79** [kandalf/cdmon_updater#1]
Hola Leo, tocayo! :)

Estoy intentando usar tu actualizador de dyndns de CDMON pero me encuentro con el siguiente problema:

root@lcg-pi:~# cdmon_updater
/usr/local/rvm/gems/ruby-2.3.0/gems/cdmon_updater-0.2.0/lib/cdmon_updater/mailer.rb:76:in 'rescue in send_mail': uninitialized constant CDMonUpdater::Mailer::CDMon (NameError)
        from /usr/local/rvm/gems/ruby-2.3.0/gems/cdmon_updater-0.2.0/lib/cdmon_updater/mailer.rb:65:in 'send_mail'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/cdmon_updater-0.2.0/lib/cdmon_updater.rb:47:in 'send_error_mail'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/cdmon_updater-0.2.0/lib/cdmon_updater.rb:37:in 'log_all'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/cdmon_updater-0.2.0/lib/ip_updater.rb:47:in 'rescue in update'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/cdmon_updater-0.2.0/lib/ip_updater.rb:23:in 'update'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/cdmon_updater-0.2.0/bin/cdmon_updater:14:in 'top (required)'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/cdmon_updater:23:in 'load'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/cdmon_updater:23:in 'main'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in 'eval'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in 'main'

No tengo ni idea de Ruby, pero suena a problema de includes o algo así al instanciar el objeto Mailer...

O puede ser que estoy intentando enviar el correo sin autenticar la conexión SMTP, ya que no quiero estar poniendo la contraseña para algo que no debería ser necesario, si puedo enviarlo por el smtp de localhost. ¿Es posible que no esté soportado este envío del mensaje sin autenticación?

gracias majo!

**Comment by kandalf** [comment]
@lcg79 Hola! Dejame verlo, porque hace rato que no toco nada de esto.

**Comment by kandalf** [comment]
@lcg79 El error que estás viendo es por un error de sintaxis, pero está saltando ahí porque está fallando el envío del email.
Para enviar el email, necesita la configuración correcta en el archivo de configuración cómo dice el README.

Si tu servidor de SMTP local permite el envío sin autenticación, no debería ser necesario poner el usuario y la contraseña.

Voy a intentar replicar el escenario con un servidor SMTP local para tratar de reproducir el error, pero no puedo garantizarte mucha velocidad en esto.

Mientras tanto, podrías pasarme tu archivo de configuración?

**Comment by lcg79** [comment]
Perdona, olvidé contestar. Ya no lo necesito. gracias!
